_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.13.0
            "5": 0.20.1
            "10":
                - 21
            "12": 0.20.1
            "13": darwin-arm64
purpose:
    value: Testing wandb integration
test:
    value: true
